name: pull-image-from-dockerhub
run-name: pull new image from docker hub
on:
    workflow_run:
        workflows: ["push-new-image"]
        types:
          - completed
jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
        - name: Set up QEMU (docker in docker)
          uses: docker/setup-qemu-action@v2
      
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: pull and run
          run: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/custom-action:${{ github.sha }}
            docker run ${{ secrets.DOCKERHUB_USERNAME }}/custom-action:${{ github.sha }}